---
title: ESS 320 Lab 4
author: Rachel Delorie
format: html
execute:
  echo: true
---
```{r}
# setup
remotes::install_github("lter/lterdatasampler")
library(tidyverse)
library(ggpubr)
library(lterdatasampler)
library(car)
library(visdat)
?and_vertebrates
```

```{r}
and_vertebrates %>% 
  filter(species == "Cutthroat trout") %>%  
  drop_na(unittype) %>% 
  count(unittype)
vis_dat(and_vertebrates) 

# First clean the dataset to create the contingency table from
trout_clean <- and_vertebrates  |>  
  #filter Cutthroat trout
  filter(species == "Cutthroat trout") |> 
  # lets test using just the 3 most abundant unittypes
  filter(unittype %in% c("C", "P", "SC")) |> 
  # drop NAs for both unittype and section
  drop_na(unittype, section)

cont_table <- table(trout_clean$section, trout_clean$unittype)

chisq.test(cont_table)
trout_clean  |>  
  count(unittype, section)  |>  
  ggpubr::ggbarplot(x = 'unittype', y = 'n', 
                    fill = 'section', 
                    palette = c("#00AFBB", "#E7B800"),
                    add = "mean_se") 
```
```{r}
trout_clean |> 
  drop_na(weight_g) |> 
  ggpubr::ggviolin(x = "section", 
                   y     = "weight_g", 
                   add   = "boxplot",
                   color = "section",
                   palette = c("#00AFBB", "#E7B800")) 
```
```{r}
cc_weight <- trout_clean |> 
  filter(section == "CC") |> 
  pull(weight_g)

og_weight <- trout_clean |> 
  filter(section == "OG") |> 
  pull(weight_g)

var.test(cc_weight, og_weight)

ggpubr::ggarrange(ggpubr::gghistogram(cc_weight, main = "Clear Cut"), 
                  ggpubr::gghistogram(og_weight, main = "Old Growth"))
var.test(log(cc_weight), log(og_weight))
```
```{r}
var.test(log(cc_weight), log(og_weight))

t.test(log(trout_clean$weight_g) ~ trout_clean$section, var.equal = TRUE)

t.test(trout_clean$weight_g ~ trout_clean$section, var.equal = FALSE)
```
```{r}
sally_clean <- and_vertebrates |> 
  filter(species == "Coastal giant salamander") |> 
  drop_na(length_2_mm, weight_g)

ggarrange(gghistogram(sally_clean$length_2_mm, title = "Length"),
gghistogram(sally_clean$weight_g, title = "Weight"))

s <- sally_clean |> 
  slice_sample(n = 5000) 

shapiro.test(s$length_2_mm)
shapiro.test(s$weight_g)

ggarrange(
 gghistogram(log(sally_clean$length_2_mm), title = "Length"), 
 gghistogram(log(sally_clean$weight_g), title = "Weight") )

cor.test(log(sally_clean$length_2_mm), log(sally_clean$weight_g))

sally_clean |> 
  mutate(log_length = log(length_2_mm), log_weight = log(weight_g)) |> 
  ggscatter(x = 'log_length', 
            y = 'log_weight', 
            alpha = .35,
            add = "loess")
```
```{r}
# spearmen
cor.test(sally_clean$length_2_mm, sally_clean$weight_g, method = "spearman")
```







